import type { RoofOption } from '@/types'

export const ROOF_OPTIONS: RoofOption[] = [
  {
    id: 'cool-roof',
    name: 'Cool Roof Coating',
    shortDescription: 'Reflective coating. Fastest ROI, zero structural demand.',
    fullDescription: 'White elastomeric coating reduces surface temp by up to 38°F, cutting cooling loads. Qualifies for Georgia Power rebates. Correct answer for most pre-1980 buildings.',
    costPerSqFt: 1.50, annualSavingsPerSqFt: 0.45, co2TonsPerSqFtPerYear: 0.0015,
    structuralLoadPSF: 0, feasibilityBase: 95,
    rebates: ['Georgia Power: $0.15/sq ft', 'Federal Energy Tax Credit'],
    warningFlags: [],
    bestFor: 'Any building. Essential for pre-1980 construction.',
  },
  {
    id: 'solar',
    name: 'Solar Panels',
    shortDescription: 'Grid-tied solar with Georgia Power net metering.',
    fullDescription: 'Monocrystalline panels with string inverters. Best on flat roofs with high sun exposure and post-1980 construction.',
    costPerSqFt: 8.00, annualSavingsPerSqFt: 1.20, co2TonsPerSqFtPerYear: 0.008,
    structuralLoadPSF: 4, feasibilityBase: 80,
    rebates: ['Federal ITC 30%', 'Georgia Power net metering', 'SREC market eligible'],
    warningFlags: ['4 lbs/sq ft — verify structural capacity for pre-1980 buildings'],
    bestFor: 'Post-1980 flat roofs with high sun exposure.',
  },
  {
    id: 'green-roof-extensive',
    name: 'Green Roof (Extensive)',
    shortDescription: 'Lightweight sedum layer. Stormwater retention and insulation.',
    fullDescription: '2–4 inch growing medium. Retains 60–80% of rainfall, reduces stormwater fees and urban heat. Low maintenance.',
    costPerSqFt: 10.00, annualSavingsPerSqFt: 0.80, co2TonsPerSqFtPerYear: 0.006,
    structuralLoadPSF: 12, feasibilityBase: 70,
    rebates: ['City of Atlanta Stormwater Credit', 'Green Building Certification'],
    warningFlags: ['12 lbs/sq ft — not for pre-1960 buildings without structural review'],
    bestFor: 'Post-1980 flat roofs. Community-facing buildings.',
  },
  {
    id: 'green-roof-intensive',
    name: 'Green Roof (Intensive)',
    shortDescription: 'Full rooftop garden. Revenue potential, high community impact.',
    fullDescription: 'Deep-soil garden with trees and seating. Revenue through events or leasing. Requires licensed structural engineer sign-off.',
    costPerSqFt: 25.00, annualSavingsPerSqFt: 1.50, co2TonsPerSqFtPerYear: 0.012,
    structuralLoadPSF: 100, feasibilityBase: 40,
    rebates: ['City of Atlanta Green Space Grant', 'LEED certification value'],
    warningFlags: [
      '⚠ Requires licensed structural engineer sign-off',
      '⚠ 80–150 lbs/sq ft — most Atlanta buildings cannot support without modification',
    ],
    bestFor: 'Modern buildings (post-2000). Community or retail use.',
  },
  {
    id: 'rainwater',
    name: 'Rainwater Harvesting',
    shortDescription: 'Cistern system. Cuts stormwater fees immediately.',
    fullDescription: 'Cistern collects rainfall for irrigation and non-potable use. With Atlanta\'s 50 in/yr rainfall, immediate stormwater fee reduction. Pairs well with any roof treatment.',
    costFixed: 12000, annualSavingsFixed: 1800, co2TonsPerYear: 0.5,
    structuralLoadPSF: 2, feasibilityBase: 88,
    rebates: ['City of Atlanta Stormwater Retention Credit'],
    warningFlags: [],
    bestFor: 'Any flat roof. Best paired with green roof or cool roof.',
  },
  {
    id: 'beekeeping',
    name: 'Rooftop Beekeeping',
    shortDescription: 'Atlanta-legal hives. High revenue per sq ft, minimal load.',
    fullDescription: 'Atlanta permits rooftop beehives (City Code § 114-434). 2-hive setup: 100–200 lbs honey/yr plus pollination contracts. Fastest ROI of any option.',
    costFixed: 4000, annualRevenueFixed: 3500, co2TonsPerYear: 0.2,
    structuralLoadPSF: 1, feasibilityBase: 92,
    rebates: [],
    warningFlags: ['Requires City of Atlanta beekeeping permit', 'Check lease restrictions'],
    bestFor: 'Any building. Strongest near restaurants or retail.',
  },
]
